### ISSUE TITLE
toPromise deprecated

### ISSUE THREAD

**Issue by yoinergomez** [jvaldesgonzalez/castia-challenge#2]
# Documentation
https://rxjs.dev/deprecations/to-promise

https://github.com/jvaldesgonzalez/castia-challenge/blob/5e1f3d0c652836dbf040ab884d26dc09e40d41a1/src/github-users/providers/github-api.ts#L26

**Comment by jvaldesgonzalez** [comment]
Fixed  PR #3 , merging
